#ifndef _USER_INPUT
#define _USER_INPUT

#include <GLFW/glfw3.h>

typedef enum {
    UIN_MOUSE_BUTTON_1 = GLFW_MOUSE_BUTTON_1,
    UIN_MOUSE_BUTTON_2 = GLFW_MOUSE_BUTTON_2,
    UIN_MOUSE_BUTTON_3 = GLFW_MOUSE_BUTTON_3,
    UIN_MOUSE_BUTTON_4 = GLFW_MOUSE_BUTTON_4,
    UIN_MOUSE_BUTTON_5 = GLFW_MOUSE_BUTTON_5,
    UIN_MOUSE_BUTTON_6 = GLFW_MOUSE_BUTTON_6,
    UIN_MOUSE_BUTTON_7 = GLFW_MOUSE_BUTTON_7,
    UIN_MOUSE_BUTTON_8 = GLFW_MOUSE_BUTTON_8,
    UIN_MOUSE_BUTTON_LAST = GLFW_MOUSE_BUTTON_LAST,
    UIN_MOUSE_BUTTON_LEFT = GLFW_MOUSE_BUTTON_LEFT,
    UIN_MOUSE_BUTTON_RIGHT = GLFW_MOUSE_BUTTON_RIGHT,
    UIN_MOUSE_BUTTON_MIDDLE = GLFW_MOUSE_BUTTON_MIDDLE,
} UinMouseButton;

typedef enum {
    UIN_KEY_SPACE = GLFW_KEY_SPACE,
    UIN_KEY_APOSTROPHE = GLFW_KEY_APOSTROPHE,
    UIN_KEY_COMMA = GLFW_KEY_COMMA,
    UIN_KEY_MINUS = GLFW_KEY_MINUS,
    UIN_KEY_PERIOD = GLFW_KEY_PERIOD,
    UIN_KEY_SLASH = GLFW_KEY_SLASH,
    UIN_KEY_0 = GLFW_KEY_0,
    UIN_KEY_1 = GLFW_KEY_1,
    UIN_KEY_2 = GLFW_KEY_2,
    UIN_KEY_3 = GLFW_KEY_3,
    UIN_KEY_4 = GLFW_KEY_4,
    UIN_KEY_5 = GLFW_KEY_5,
    UIN_KEY_6 = GLFW_KEY_6,
    UIN_KEY_7 = GLFW_KEY_7,
    UIN_KEY_8 = GLFW_KEY_8,
    UIN_KEY_9 = GLFW_KEY_9,
    UIN_KEY_SEMICOLON = GLFW_KEY_SEMICOLON,
    UIN_KEY_EQUAL = GLFW_KEY_EQUAL,
    UIN_KEY_A = GLFW_KEY_A,
    UIN_KEY_B = GLFW_KEY_B,
    UIN_KEY_C = GLFW_KEY_C,
    UIN_KEY_D = GLFW_KEY_D,
    UIN_KEY_E = GLFW_KEY_E,
    UIN_KEY_F = GLFW_KEY_F,
    UIN_KEY_G = GLFW_KEY_G,
    UIN_KEY_H = GLFW_KEY_H,
    UIN_KEY_I = GLFW_KEY_I,
    UIN_KEY_J = GLFW_KEY_J,
    UIN_KEY_K = GLFW_KEY_K,
    UIN_KEY_L = GLFW_KEY_L,
    UIN_KEY_M = GLFW_KEY_M,
    UIN_KEY_N = GLFW_KEY_N,
    UIN_KEY_O = GLFW_KEY_O,
    UIN_KEY_P = GLFW_KEY_P,
    UIN_KEY_Q = GLFW_KEY_Q,
    UIN_KEY_R = GLFW_KEY_R,
    UIN_KEY_S = GLFW_KEY_S,
    UIN_KEY_T = GLFW_KEY_T,
    UIN_KEY_U = GLFW_KEY_U,
    UIN_KEY_V = GLFW_KEY_V,
    UIN_KEY_W = GLFW_KEY_W,
    UIN_KEY_X = GLFW_KEY_X,
    UIN_KEY_Y = GLFW_KEY_Y,
    UIN_KEY_Z = GLFW_KEY_Z,
    UIN_KEY_LEFT_BRACKET = GLFW_KEY_LEFT_BRACKET,
    UIN_KEY_BACKSLASH = GLFW_KEY_BACKSLASH,
    UIN_KEY_RIGHT_BRACKET = GLFW_KEY_RIGHT_BRACKET,
    UIN_KEY_GRAVE_ACCENT = GLFW_KEY_GRAVE_ACCENT,
    UIN_KEY_WORLD_1 = GLFW_KEY_WORLD_1,
    UIN_KEY_WORLD_2 = GLFW_KEY_WORLD_2,
    UIN_KEY_ESCAPE = GLFW_KEY_ESCAPE,
    UIN_KEY_ENTER = GLFW_KEY_ENTER,
    UIN_KEY_TAB = GLFW_KEY_TAB,
    UIN_KEY_BACKSPACE = GLFW_KEY_BACKSPACE,
    UIN_KEY_INSERT = GLFW_KEY_INSERT,
    UIN_KEY_DELETE = GLFW_KEY_DELETE,
    UIN_KEY_RIGHT = GLFW_KEY_RIGHT,
    UIN_KEY_LEFT = GLFW_KEY_LEFT,
    UIN_KEY_DOWN = GLFW_KEY_DOWN,
    UIN_KEY_UP = GLFW_KEY_UP,
    UIN_KEY_PAGE_UP = GLFW_KEY_PAGE_UP,
    UIN_KEY_PAGE_DOWN = GLFW_KEY_PAGE_DOWN,
    UIN_KEY_HOME = GLFW_KEY_HOME,
    UIN_KEY_END = GLFW_KEY_END,
    UIN_KEY_CAPS_LOCK = GLFW_KEY_CAPS_LOCK,
    UIN_KEY_SCROLL_LOCK = GLFW_KEY_SCROLL_LOCK,
    UIN_KEY_NUM_LOCK = GLFW_KEY_NUM_LOCK,
    UIN_KEY_PRINT_SCREEN = GLFW_KEY_PRINT_SCREEN,
    UIN_KEY_PAUSE = GLFW_KEY_PAUSE,
    UIN_KEY_F1 = GLFW_KEY_F1,
    UIN_KEY_F2 = GLFW_KEY_F2,
    UIN_KEY_F3 = GLFW_KEY_F3,
    UIN_KEY_F4 = GLFW_KEY_F4,
    UIN_KEY_F5 = GLFW_KEY_F5,
    UIN_KEY_F6 = GLFW_KEY_F6,
    UIN_KEY_F7 = GLFW_KEY_F7,
    UIN_KEY_F8 = GLFW_KEY_F8,
    UIN_KEY_F9 = GLFW_KEY_F9,
    UIN_KEY_F10 = GLFW_KEY_F10,
    UIN_KEY_F11 = GLFW_KEY_F11,
    UIN_KEY_F12 = GLFW_KEY_F12,
    UIN_KEY_F13 = GLFW_KEY_F13,
    UIN_KEY_F14 = GLFW_KEY_F14,
    UIN_KEY_F15 = GLFW_KEY_F15,
    UIN_KEY_F16 = GLFW_KEY_F16,
    UIN_KEY_F17 = GLFW_KEY_F17,
    UIN_KEY_F18 = GLFW_KEY_F18,
    UIN_KEY_F19 = GLFW_KEY_F19,
    UIN_KEY_F20 = GLFW_KEY_F20,
    UIN_KEY_F21 = GLFW_KEY_F21,
    UIN_KEY_F22 = GLFW_KEY_F22,
    UIN_KEY_F23 = GLFW_KEY_F23,
    UIN_KEY_F24 = GLFW_KEY_F24,
    UIN_KEY_F25 = GLFW_KEY_F25,
    UIN_KEY_KP_0 = GLFW_KEY_KP_0,
    UIN_KEY_KP_1 = GLFW_KEY_KP_1,
    UIN_KEY_KP_2 = GLFW_KEY_KP_2,
    UIN_KEY_KP_3 = GLFW_KEY_KP_3,
    UIN_KEY_KP_4 = GLFW_KEY_KP_4,
    UIN_KEY_KP_5 = GLFW_KEY_KP_5,
    UIN_KEY_KP_6 = GLFW_KEY_KP_6,
    UIN_KEY_KP_7 = GLFW_KEY_KP_7,
    UIN_KEY_KP_8 = GLFW_KEY_KP_8,
    UIN_KEY_KP_9 = GLFW_KEY_KP_9,
    UIN_KEY_KP_DECIMAL = GLFW_KEY_KP_DECIMAL,
    UIN_KEY_KP_DIVIDE = GLFW_KEY_KP_DIVIDE,
    UIN_KEY_KP_MULTIPLY = GLFW_KEY_KP_MULTIPLY,
    UIN_KEY_KP_SUBTRACT = GLFW_KEY_KP_SUBTRACT,
    UIN_KEY_KP_ADD = GLFW_KEY_KP_ADD,
    UIN_KEY_KP_ENTER = GLFW_KEY_KP_ENTER,
    UIN_KEY_KP_EQUAL = GLFW_KEY_KP_EQUAL,
    UIN_KEY_LEFT_SHIFT = GLFW_KEY_LEFT_SHIFT,
    UIN_KEY_LEFT_CONTROL = GLFW_KEY_LEFT_CONTROL,
    UIN_KEY_LEFT_ALT = GLFW_KEY_LEFT_ALT,
    UIN_KEY_LEFT_SUPER = GLFW_KEY_LEFT_SUPER,
    UIN_KEY_RIGHT_SHIFT = GLFW_KEY_RIGHT_SHIFT,
    UIN_KEY_RIGHT_CONTROL = GLFW_KEY_RIGHT_CONTROL,
    UIN_KEY_RIGHT_ALT = GLFW_KEY_RIGHT_ALT,
    UIN_KEY_RIGHT_SUPER = GLFW_KEY_RIGHT_SUPER,
    UIN_KEY_MENU = GLFW_KEY_MENU,
    UIN_KEY_LAST = GLFW_KEY_LAST,
} UinKey;

typedef enum {
    UIN_CURSOR_NORMAL = GLFW_CURSOR_NORMAL,
    UIN_CURSOR_HIDDEN = GLFW_CURSOR_HIDDEN,
    UIN_CURSOR_DISABLED = GLFW_CURSOR_DISABLED,
    UIN_CURSOR_CAPTURED = GLFW_CURSOR_CAPTURED,
} UinCursorMode;

// User input init
void uin_init(GLFWwindow *window);

// Call this at the end of the frame, resets all mouse button and key arrays so
// functions like uin_is_mouse_button_pressed() return accurate results.
void uin_refresh(void);

int uin_is_mouse_button_down(UinMouseButton button);
int uin_is_mouse_button_pressed(UinMouseButton button);
int uin_is_mouse_button_released(UinMouseButton button);

int uin_is_key_down(UinKey key);
int uin_is_key_pressed(UinKey key);
int uin_is_key_released(UinKey key);

void uin_set_cursor(UinCursorMode mode);
void uin_get_mouse_pos(double *out_x, double *out_y);
void uin_get_mouse_delta(double *out_x, double *out_y);

float uin_get_scroll(void);
float uin_get_scroll_horizontal(void);

#endif
